import { useQuery } from '@tanstack/react-query'
import { useState } from 'react'
import { api } from '../../api/client'

export function MemoryExplorerPage() {
  const [subject, setSubject] = useState('')
  const [status, setStatus] = useState('active')
  const [asOf, setAsOf] = useState('2026-10-21')
  const notes = useQuery({ queryKey: ['memory-notes', subject, status, asOf], queryFn: () => api.listMemoryNotes({ subject: subject || undefined, status: status || undefined, as_of: asOf || undefined, limit: 100 }) })
  return <div className="p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-lg font-bold text-ink">Memory Explorer</h1><p className="text-sm text-ink-muted">Governed persistent notes with validity and lifecycle state.</p></div><div className="flex flex-wrap gap-2"><label className="text-xs text-ink-faint">Subject<input value={subject} onChange={(event) => setSubject(event.target.value)} placeholder="CUS-…" className="ml-2 rounded border border-border bg-surface-1 px-2 py-1 font-mono text-ink" /></label><label className="text-xs text-ink-faint">Status<select value={status} onChange={(event) => setStatus(event.target.value)} className="ml-2 rounded border border-border bg-surface-1 px-2 py-1 text-ink"><option value="">all</option><option>active</option><option>superseded</option><option>retracted</option><option>expired</option></select></label><label className="text-xs text-ink-faint">As of<input type="date" value={asOf} onChange={(event) => setAsOf(event.target.value)} className="ml-2 rounded border border-border bg-surface-1 px-2 py-1 font-mono text-ink" /></label></div></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{notes.data?.items.map((note) => <article key={note.note_id} className="rounded-lg border border-border bg-surface-2 p-4"><div className="flex items-center justify-between"><span className="font-mono text-xs text-cyan">{note.note_id}</span><span className={`rounded px-2 py-0.5 text-[10px] uppercase ${note.status === 'active' ? 'bg-emerald/10 text-emerald' : 'bg-surface-3 text-ink-muted'}`}>{note.status}</span></div><p className="mt-2 text-sm text-ink">{note.content}</p><div className="mt-3 flex flex-wrap gap-1">{note.tags.map((tag) => <span key={tag} className="rounded bg-surface-1 px-1.5 py-0.5 text-[10px] text-ink-muted">{tag}</span>)}</div><p className="mt-3 font-mono text-[10px] text-ink-faint">{note.scope} · confidence {note.confidence.toFixed(2)} · valid {note.valid_from ?? '—'} → {note.valid_to ?? 'open'}</p><p className="mt-1 truncate font-mono text-[10px] text-ink-faint">sources {note.source_refs.join(', ')}</p></article>)}</div>{notes.data?.items.length === 0 && <p className="mt-6 text-sm text-ink-faint">No eligible notes.</p>}</div>
}
